rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"
  queue: "db_status_pool"
  exchange: ""

server:
  port: 8080
  host: "localhost"
  env: "dev"

ratelimit:
  max: 20
  expiration: 30